### ISSUE TITLE
Workflow for generating EBEs, simulating individual exposures and calculating Cmax, Cmin and AUC 

### ISSUE THREAD

**Issue by akurumaddali** [NMautoverse/NMsim#9]
There is a Pop PK model in NONMEM. I would like to generate post-hoc EBEs with maxeval=0, and compute corresponding Cmax, Cmin and AUC for each subject at cycle 1 and at cycle 10 using a new dosing regimen (for I.V. infusion: initial dose at cycle 1 = x mg/kg * BW for 2 hrs followed by dose of x mg/kg *BW for 1 hr until cycle 10/steady-state). Could you please provide the steps to be followed to do this task using NMsim? Thanks in advance.

**Comment by philipdelff** [comment]
Please see the vignette on the topic on simulation using EBE's:
https://philipdelff.github.io/NMsim/articles/NMsim-known.html
You may also want to look at the one on creating simulation data sets:
https://philipdelff.github.io/NMsim/articles/NMsim-DataCreate.html

Feel free to reopen if something is unclear or you have further questions.
